collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4226638
  brandStrength: 0.5773362
  lightness: 0.2851772
  brandColors:
    - '#231F1E'
    - '#FFFEFF'
    - '#7C90AB'
    - '#CADEE5'
    - '#5F605B'
  rhythmicContrast: 0.4129968
typography_spectrum: 0.1895811
layout_spectrum: 0.915682
name: gresch
