layout_spectrum: 0.3327787
typography_spectrum: 0.9787019
color:
  saturation: 0.7525278
  lightness: 0.7103878
  brandStrength: 0.5773362
  brandColors:
    - '#392E20'
    - '#897E65'
    - '#BCAC89'
    - '#BD8839'
    - '#7F4B1F'
  rhythmicContrast: 0.9452097
name: gresch
